# Generated by Django 5.0.6 on 2024-05-26 09:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField()),
                ('field', models.CharField(blank=True, choices=[('ВС', 'Восточно-Сургутское'), ('ВТК', 'Восточно-Токайское'), ('ВПР', 'Восточно-Правдинское'), ('ВСТР', 'Встречное'), ('ЕФР', 'Ефремовское'), ('ЗУГ', 'Западно-Угутское'), ('КИН', 'Киняминское'), ('КУЗ', 'Кузоваткинское'), ('КУДР', 'Кудринское'), ('МБ', 'Малобалыкское'), ('МАМ', 'Мамонтовское'), ('МАЙ', 'Майское'), ('МОСК', 'Московцева'), ('ОМБ', 'Омбинское'), ('ПЕТ', 'Петелинское'), ('ПРД', 'Правдинское'), ('ПРОп', 'Приобское (правый)'), ('ПРОл', 'Приобское (левый)'), ('ЭРГ', 'Эргинское'), ('ПРЗ', 'Приразломное'), ('САЛ', 'Салымское'), ('СОЛ', 'Солкинское'), ('СОР', 'Соровское'), ('СБ', 'Среднебалыкское'), ('СУГ', 'Среднеугутское'), ('УГ', 'Угутское'), ('УБ', 'Усть-Балыкское'), ('ФН', 'Фаинское'), ('ЮБ', 'Южно-Балыкское'), ('ЮТЕПЛ', 'Южно-Тепловское'), ('ЮС', 'Южно-Сургутское')])),
                ('first_stage_date', models.DateField(blank=True)),
                ('second_stage_date', models.DateField(blank=True)),
                ('required_capacity', models.IntegerField(choices=[(400, '400'), (320, '320'), (270, '270'), (250, '250'), (225, '225'), (200, '200'), (0, '0')])),
                ('required_mud', models.CharField(blank=True, choices=[('РУО', 'РУО'), ('РВО', 'РВО')])),
                ('gs_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('nns_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('marker', models.CharField(choices=[('нет', 'обычный куст'), ('для 2эш', 'для 2эш'), ('СНПХ', 'возможно бурение СНПХ'), ('приоритет', 'приоритетное движение')], default='нет')),
                ('status', models.CharField(choices=[('free', 'Free'), ('drilled', 'Drilled'), ('drilling', 'Drilling'), ('reserved', 'Reserved')], default='free')),
            ],
            options={
                'ordering': ['first_stage_date'],
            },
        ),
        migrations.CreateModel(
            name='type_of_DR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrillingRig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(unique=True)),
                ('mud', models.CharField(choices=[('РУО', 'РУО'), ('РВО', 'РВО')])),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.contractor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.type_of_dr')),
            ],
            options={
                'ordering': ['contractor', 'type'],
            },
        ),
        migrations.CreateModel(
            name='RigPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('drilling_rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.drillingrig')),
                ('pad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.pad')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
        migrations.CreateModel(
            name='PositionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_rating', models.FloatField()),
                ('first_stage_date_rating', models.FloatField()),
                ('downtime_days', models.IntegerField()),
                ('second_stage_date_rating', models.FloatField()),
                ('mud_rating', models.FloatField()),
                ('logistic_rating', models.FloatField()),
                ('marker_rating', models.FloatField()),
                ('common_rating', models.FloatField()),
                ('status', models.CharField(default='')),
                ('next_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.pad')),
                ('current_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.rigposition')),
            ],
            options={
                'ordering': ['current_position'],
            },
        ),
        migrations.CreateModel(
            name='NextPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('default', 'Требуется подтверждение'), ('empty', 'Отсутствуют кандидаты'), ('commited', 'Подтверждено'), ('deleted', 'Удалено пользователем'), ('changed', 'Изменено. Требуется подтверждение')], default='default')),
                ('next_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.pad')),
                ('current_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dvizhenie.rigposition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
