# Generated by Django 5.0.1 on 2024-01-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvizhenie', '0004_alter_pad_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingrig',
            name='mud',
            field=models.CharField(choices=[('', 'Выберите тип бурового раствора'), ('РУО', 'РУО'), ('РВО', 'РВО')]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='first_stage_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pad',
            name='required_capacity',
            field=models.IntegerField(choices=[(0, 'Выберите требуемую грузоподъемность'), (400, '400'), (320, '320'), (270, '270'), (250, '250'), (225, '225'), (200, '200')], default=0),
        ),
        migrations.AlterField(
            model_name='pad',
            name='required_mud',
            field=models.CharField(choices=[('', 'Выберите тип бурового раствора'), ('РУО', 'РУО'), ('РВО', 'РВО')], default=''),
        ),
        migrations.AlterField(
            model_name='pad',
            name='second_stage_date',
            field=models.DateField(),
        ),
    ]
