# Generated by Django 5.0.1 on 2024-01-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvizhenie', '0005_alter_drillingrig_mud_alter_pad_first_stage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingrig',
            name='mud',
            field=models.CharField(choices=[('РУО', 'РУО'), ('РВО', 'РВО')]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='field',
            field=models.CharField(blank=True, choices=[('ВС', 'Восточно-Сургутское'), ('ВТК', 'Восточно-Токайское'), ('ВПР', 'Восточно-Правдинское'), ('ВСТР', 'Встречное'), ('ЕФР', 'Ефремовское'), ('ЗУГ', 'Западно-Угутское'), ('КИН', 'Киняминское'), ('КУЗ', 'Кузоваткинское'), ('КУДР', 'Кудринское'), ('МБ', 'Малобалыкское'), ('МАМ', 'Мамонтовское'), ('МАЙ', 'Майское'), ('МОСК', 'Московцева'), ('ОМБ', 'Омбинское'), ('ПЕТ', 'Петелинское'), ('ПРД', 'Правдинское'), ('ПРОп', 'Приобское (правый)'), ('ПРОл', 'Приобское (левый)'), ('ЭРГ', 'Эргинское'), ('ПРЗ', 'Приразломное'), ('САЛ', 'Салымское'), ('СОЛ', 'Солкинское'), ('СОР', 'Соровское'), ('СБ', 'Среднебалыкское'), ('СУГ', 'Среднеугутское'), ('УГ', 'Угутское'), ('УБ', 'Усть-Балыкское'), ('ФН', 'Фаинское'), ('ЮБ', 'Южно-Балыкское'), ('ЮТЕПЛ', 'Южно-Тепловское'), ('ЮС', 'Южно-Сургутское')]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='first_stage_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='required_capacity',
            field=models.IntegerField(choices=[(400, '400'), (320, '320'), (270, '270'), (250, '250'), (225, '225'), (200, '200'), (0, '0')]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='required_mud',
            field=models.CharField(blank=True, choices=[('РУО', 'РУО'), ('РВО', 'РВО')]),
        ),
        migrations.AlterField(
            model_name='pad',
            name='second_stage_date',
            field=models.DateField(blank=True),
        ),
    ]
