# Generated by Django 5.0.1 on 2024-01-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvizhenie', '0007_alter_nextposition_current_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='status',
            field=models.CharField(default=''),
        ),
    ]
