# Generated by Django 5.0.1 on 2024-02-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvizhenie', '0008_pad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigposition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rigposition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
