# Generated by Django 5.0.1 on 2024-02-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvizhenie', '0010_alter_pad_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionrating',
            options={'ordering': ['current_position']},
        ),
        migrations.RemoveField(
            model_name='positionrating',
            name='current_position_end_date',
        ),
    ]
